### ISSUE TITLE
登录后报错

### ISSUE THREAD

**Issue by ghost** [This-is-XiaoDeng/qcli#1]
报错内容如下：
─────────────────────────────────────────── QCLI (By XiaoDeng3386) ───────────────────────────────────────────
╭──────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────╮
│ /home/Meow/.local/lib/python3.7/site-packages/textual/message_pump.py:161 in _get_message                  │
│                                                                                                            │
│   158 │   │   │   finally:                                                                                 │
│   159 │   │   │   │   self._pending_message = None                                                         │
│   160 │   │                                                                                                │
│ ❱ 161 │   │   message = await self._message_queue.get()                                                    │
│   162 │   │                                                                                                │
│   163 │   │   if message is None:                                                                          │
│   164 │   │   │   self._closed = True                                                                      │
│                                                                                                            │
│ ╭──────────────────────────────── locals ────────────────────────────────╮                                 │
│ │ self = QCli(title='IT CRAFT QCLI Version 1.2', classes={'-dark-mode'}) │                                 │
│ ╰────────────────────────────────────────────────────────────────────────╯                                 │
│                                                                                                            │
│ /usr/lib/python3.7/asyncio/queues.py:159 in get                                                            │
│                                                                                                            │
│   156 │   │   │   getter = self._loop.create_future()                                                      │
│   157 │   │   │   self._getters.append(getter)                                                             │
│   158 │   │   │   try:                                                                                     │
│ ❱ 159 │   │   │   │   await getter                                                                         │
│   160 │   │   │   except:                                                                                  │
│   161 │   │   │   │   getter.cancel()  # Just in case getter is not done yet.                              │
│   162 │   │   │   │   try:                                                                                 │
│                                                                                                            │
│ ╭──────────────────────────────────────────────── locals ────────────────────────────────────────────────╮ │
│ │ getter = <Future finished result=None>                                                                 │ │
│ │   self = <Queue at 0x7f114bc2b6a0 maxsize=0 _queue=[StylesUpdated(Screen(id='_default')), Ready()]     │ │
│ │          tasks=8>                                                                                      │ │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Task <Task pending coro=<App.run_async() running at 
/home/Meow/.local/lib/python3.7/site-packages/textual/app.py:929>> got Future <Future pending> attached to a 
different loop
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 36, in display_cqhttp_logger
    buffer = self.cqhttp_popen.stdout.readline().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 78: invalid continuation byte

**Comment by This-is-XiaoDeng** [comment]
已阅，等待处理

**Comment by ghost** [comment]
6

**Comment by This-is-XiaoDeng** [comment]
> 6

抱歉主要是要考试没空哈

**Comment by ghost** [comment]
没看见，非常抱歉（

**Comment by This-is-XiaoDeng** [comment]
已尝试修复，现在试试？
